---
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```
class: center, middle

# Considerations

???

---

.pull-left[
#Advantages

* Pragmatic approach

* May be appropriate if limited in time and resources

* Useful for mixed methods research or developing interventions
]

???

---

.pull-left[
#Considerations

* Reputation of being low-quality 

* Limited guidance 

* 'Method slurring' 
]

???

In terms of the quality of research design, qualitative description has developed a reputation for being low-quality. Critiques of the approach often stem from it not having clear criteria to determine what is "good" qualitative research (Caelli et al., 2003, p.3). As Sandelowski (2000, p.334) explained, the hierarchy for evidence-based research values "prediction and control" as the gold standard. As a result, researchers may feel the need to defend their study as being more than a description, and attempt to position their research as phenomenology, grounded theory, ethnography, narrative inquiry, or a case study without actually involving the characteristics of the approach, or engaging in the complex design (Sandelowski, 2000). However, with qualitative research, there is no universal set of criteria for evaluating quality. Rather, like Caelli et al. (2003, p.4) states, "each qualitative approach needs to be evaluated in a manner that is congruent with its epistemological and methodological origins".



---

.pull-left[
"The value of qualitative description lies not only in the knowledge its use can produce, but also as a vehicle for presenting and treating research methods as living entities that resist simple classiﬁcation."

* (Sandelowski, 2010, p.83) 
]

???

---
