---
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```
class: center, middle

# Qualitative Description


???

The complex components of distinct qualitative approaches like phenomenology, ethnography, grounded theory, narrative or case study makes qualitative description an appealing approach for nursing research (Sandelowski, 2000).

---

class: center, middle

“It is rarely feasible for researchers to engage in a deeply theoretical and methodologically sophisticated study, yet this should not exclude clinicians from thoughtful rigorous inquiry.” 
* [Caelli et al., 2003, p.2] 

???

It's not always reasonable for clinician researchers to conduct "deeply theoretical and methodoloigcally sophisticated" qualitative studies, but that shouldn't deter them from engaging in qualitative research that maintains "thoughtful and rigorous inquiry" (Caelli et al., 2003, p.2).  

Sandelowski (2000, p.335) explains that qualitative description is it's own research method, rather than a "nursing adaptation of grounded theory, phenomenology, and ethnography". 

---

.pull-left[

* **Philosophy**: Pragmatic approach with overtones for other qualitative approaches. 

* **Theoretical orientation**: Naturalism

* **Design features**: 
** *Sampling*: Purposive sampling strategy (e.g., maximum variation)
** *Data collection*: Open-ended questions in individual or focus group interviews
** *Data analysis*: Variation of qualitative content analysis

* **Reporting results**: Descriptive summary

]

???

* Philosophy: Pragmatic approach
* Theoretical orientation: Naturalism
* Design features:
** Sampling: Purposive sampling strategies (e.g., Maximum variation)
* Data collection: Open-ended questions in individual or focus group interviews 
* Data analysis: 
** Descriptive statistics to summarize data 
** Stays close to data (low-level interpretation)
** Variation of qualitative content analysis (e.g., using "in vivo coding") 
* Reporting results: Stays close to data and describes informants' experiences in a language similar to their own langauge.
---
