---
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    nature:
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>`
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


class: center, middle

#'Models' of Evidence-Based Practice

???

It's great to know that we should be considering several different aspects like research evidence, patient values and clinical experience, to ensure we are truly practicing evidence-based healthcare, but when it comes to actually applying these principles to make a decision, we need some guidance about how best to do that. Thankfully, that's where 'models' for evidence-based practice start to become very useful.

We can think of these models as a 'guideline' of steps that we can use to understand, create, and implement evidence-based decision-making into practice. 

Various different models of EBP have been developed. Each tries in their own way to translate the general concept of EBP involving the integration of  distinct yet related dimensions like research, clinical experience and patient values into the decision-making process. 

As an initial introduction to using models for evidence-based practice, in the next exercise I'm going to show diagrams depicting two different models for conceptualizing evidence-based practice. Both of them contain basically the same elements, but have an important distinction. Take a look and see if you can pick it out. Then we'll discuss further.

---


